FROM python:3.11

ADD src/rest_api.py .
ADD src/config.py .

COPY requirements.txt .
RUN pip install -r requirements.txt

CMD ["sh", "-c", "python -m uvicorn --port ${DATABASE_PORT} --host 0.0.0.0 rest_api:app"]
