version: '3.8'

networks:
  mqtt-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.100.10.0/24

services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    user: mosquitto
    volumes:
      - type: bind
        source: ./config/
        target: /mosquitto/config/
        read_only: false
      - type: volume
        source: data
        target: /mosquitto/data/
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
    networks:
      mqtt-net:
        ipv4_address: 172.100.10.10

  mongodb:
    image: mongo
    container_name: my-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: your_username
      MONGO_INITDB_ROOT_PASSWORD: your_password
    volumes:
      - mongodb_data:/data/db
    networks:
      mqtt-net:
        ipv4_address: 172.100.10.12

  mqtt-handler:
    container_name: mqtt-handler
    build:
      context: .
      dockerfile: Dockerfile_mqtt_handler
    networks:
      mqtt-net:
        ipv4_address: 172.100.10.11
    depends_on:
      - mqtt-broker
      - mongodb
    environment:
      MQTT_BROKER_ADDRESS: 172.100.10.10
      DATABASE_URL: mongodb://172.100.10.12:27017/
      TZ: Europe/Helsinki

  rest-api:
    container_name: rest-api
    build:
      context: .
      dockerfile: Dockerfile_rest_api
    networks:
      mqtt-net:
        ipv4_address: 172.100.10.13
    depends_on:
      - mongodb
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host
    environment:
      DATABASE_URL: mongodb://172.100.10.12:27017/

volumes:
  mongodb_data:
  data:
    name: "mqtt-broker-data"
